### ISSUE TITLE
Suggestion: make the documentation single-page

### ISSUE THREAD

**Issue by sebastien-roch** [liip/kanbasu#13]
Thanks for the nice and simple framework, really like the grid and the spacing helper.
When I need to take a quick look at a particular section in the doc, it's not as quick as expected because of the 3 distinct html pages. I think that this is what makes the bootstrap documentation quite friendly when searching.
I understand you separated them because `default list` is not the same as `list component` for example, but for a small framework like this one I would just merge them. imo of course.

**Comment by jeanmonod** [comment]
Salut @sebastien-roch !!!!

**Comment by jeanmonod** [comment]
Comment vas-tu @sebastien-roch ? ;)

**Comment by LeBenLeBen** [comment]
I’m not sure I get your requirement because Bootstrap documentation is also split into multiple pages for top-level categories.

I’ll introduce a quick search field in the header to jump to a specific page/section soon, it will probably solve your issue. Keep it open until it’s available to have your feedback.

**Comment by LeBenLeBen** [comment]
Here we go, [quick search](http://kanbasu.liip.ch/) in the top right corner, hope that helps.

**Comment by sebastien-roch** [comment]
Thanks, that was quick and helps a lot!
