### ISSUE TITLE
Anchor color styling from box override any other nested anchor color property

### ISSUE THREAD

**Issue by gperriard** [liip/kanbasu#19]
Unfortunately, the color property applied on link from the box component override other color property of nested elements.
https://github.com/liip/kanbasu/blob/master/src/assets/scss/components/_box.scss#L16

For instance:

```
.box {
    color: black;
}

.box a {
    color: inherit;
}

.btn--primary {
    color: red;
)

<div class="box">
   <p>This button has not the right</p>
   <a href="#" class="btn btn--primary">color</a>
</div>
```

**Comment by LeBenLeBen** [comment]
Instead of targeting all `a` inside `.box` elements, we could target `a:not([class])` which would cover more than just buttons but all anchors. Those that would have some special styling applied wouldn’t be targeted by the color inheritance. I think that’s the best way to cover most _usual_ cases. WDYT?
