### ISSUE TITLE
Changing the unit of $font-size-default should be possible

### ISSUE THREAD

**Issue by sylvainaerni** [liip/kanbasu#53]
`$font-size-default` is used for several calculations, these calcs force the use of `px`, especially in `typography.scss`:
the html definition:
`font-size: 100% * $font-size-default / 16px;`
could be remplaced by something like:
`@if ( unit($font-size-default) == "px" ){
    font-size: 100% * $font-size-default / 16px;
  }
  @else {
    $font-size-unitless: $font-size-default / ($font-size-default * 0 + 1);
    font-size: percentage($font-size-unitless);
  }`

In the same way, the function `rem()` in `tools/functions.scss` returns an error when `$font-size-default`isn't set in `px`

**Comment by LeBenLeBen** [comment]
@sylvainaerni I’ve spend some time trying to get rid of this limitation but my main issue is the auto calculation of select’s height which is quite useful. I don’t see how I could do the same without a font-size in pixels.

Can you explain your requirements here so I can see if I can make it happen without breaking the existing behavior?

**Comment by sylvainaerni** [comment]
I guess you faced calculations with incompatible units :/ 
What I did is changing all the units from px to em (spacings, container width, etc) to tacle this unit issue. Plus the changes explained above, and it works.
I could prepare you a pull request to show you all the changes I did to make it work and discuss from there @LeBenLeBen

**Comment by LeBenLeBen** [comment]
That sounds like a lot of work and requirements for a very specific use case that can probably be achieved with custom variables and tiny overrides, no? The purpose of the framework is to handle the most common scenarios, otherwise the code and documentation will grow unexpectedly and could confuse users in their experience with the tool.

I’m not sure your suggestion would work with every unit. I would definitely have to test the solution to see how solid it is and if it’s worth adding it for everyone depending on its advantages and complexity. If you could send a PR with a usage exemple that would help me a lot understanding your requirements and try to make it happen.

**Comment by LeBenLeBen** [comment]
Closing until I get more info about the exact requirements.
